### ISSUE TITLE
Build Jet Fuel

### ISSUE THREAD

**Issue by stevekinney** [turingschool/intermission-assignments#1]
You'll be building a modified version of [Jet Fuel](https://gist.github.com/stevekinney/cac8d9374e99a0d7d4b2).

Post a link to your repository here by Monday, 2/2.

The project itself is due Saturday, 2/7.

**Comment by ghost** [comment]
git@github.com:bayendor/jetfuel.git

**Comment by skuhlmann** [comment]
https://github.com/skuhlmann/jetfuel

**Comment by trayo** [comment]
https://github.com/trayo/jet_fuel.git

**Comment by Tmee** [comment]
https://github.com/Tmee/jetfuel

**Comment by VikiAnn** [comment]
https://github.com/VikiAnn/jetfuel

**Comment by dalexj** [comment]
https://github.com/dalexj/jet_fuel

**Comment by dglunz** [comment]
https://github.com/dglunz/jet-fuel :rocket: :fuelpump:

**Comment by katelane** [comment]
https://github.com/katelane/jetfuel

**Comment by gregnar** [comment]
https://github.com/gregnar/jetfuel

**Comment by chandracarney** [comment]
https://github.com/chandracarney/jetfuel

**Comment by ChasevanHekken** [comment]
https://github.com/ChasevanHekken/jetfuel

**Comment by hjoseph96** [comment]
https://github.com/Copywright/fuel_of_jet

**Comment by zRouth** [comment]
https://github.com/zRouth/jet_fuel
