### ISSUE TITLE
Intermission Assignments - 1611 FE

### ISSUE THREAD

**Issue by martensonbj** [turingschool/intermission-assignments#105]
### Module 3 Front End Prework:

Leave links to github repos, gists, or screenshots in the comments below. Good resources for screenshots are [recordit](http://recordit.co/) or [imgur](http://imgur.com/).

**Required Assignments:**  
Wes Bos Redux Tutorial
NodeSchool Tutorials
JavaScript 30 Exercises  

Please note any additional or optional work completed - feel free to add feedback on any exercises that went well/didn't go well here also.

**Comment by martensonbj** [comment]
This is an example of how to submit your assignments: 

[WesBos Github Repo](#)  
[JS 30 Exercises Repo](#)  
![Screenshot Of Nodeschool](http://i.imgur.com/l1wSFRW.png)
`![Screenshot Of Nodeschool](http://i.imgur.com/l1wSFRW.png)` << How to link to an imgur image.

Feelings: 
The WesBos tutorial was too fast, but it was a first look at redux concepts and I'm sure I'll figure it out.   
Really like the JS30 exercises. Made me realize how much I've learned. (Etc...)

**Comment by juliankyer** [comment]
[JS30 repo](https://github.com/juliankyer/JavaScript30)
[Reduxstagram repo](https://github.com/juliankyer/Learn-Redux-Starter-Files)
![scope-chains-closures](https://cloud.githubusercontent.com/assets/21695198/23827132/b754f226-0669-11e7-8729-423620b0f5dc.png)
![expressworks](https://cloud.githubusercontent.com/assets/21695198/23827136/c498fc66-0669-11e7-9e37-e724f472ff67.png)

The Wes Bos stuff was great. Reduxstagram was a cool project and a good first look at Redux. The JS30 stuff also gave me some new ways to look at code, and I liked picking up some new stuff. I have no idea what's going on with Express, that exercise wasn't helpful as a first look. Pretty much all I picked up was that Jade is now Pug. The scope/chains/closures exercise was good, although I wish it were a little more extensive/had more practical examples.

**Comment by stacimcwilliams** [comment]
[Github repo for Wes Bos Redux tutorial](https://github.com/stacimcwilliams/Learn-Redux-Starter-Files)
[Github repo for JavaScript 30](https://github.com/stacimcwilliams/JavaScript30)
![Screenshot of NodeSchool-Scope-Chains-Closures](http://recordit.co/I2cIL63QOo.gif)
![Screenshot of NodeSchool-Express](http://recordit.co/nJWgxNoti5.gif)
The JS30 stuff was really good some of it I could follow along really well and some of it was really new but cool. The Redux tutorial was interesting, although I'm not sure how much I retained from it because he moved through it so quickly and so much of it was new material. As for the node school I liked the scope-chains-closures exercises and wish there had been more of them. The express ones I didn't feel were helpful as I had to use the videos to get through them and had no context for what I was doing.

**Comment by becs919** [comment]
[Wes Bos Redux Repo](https://github.com/becs919/learn-redux)
[JS 30 Repo](https://github.com/becs919/javascript-30)
![Screenshot of Nodeschool - Scopes, Chains, Closures](http://i.imgur.com/1TWP8sA.png)
![Screenshot of Nodeschool - ExpressWorks](http://i.imgur.com/QS5UOXB.png)

I really enjoyed the Reduxtagram tutorial - it was a good intro to redux. It moved a little fast for me, so I am not sure how much stuck with me. The Javascript 30 challenges were really interesting. I liked all of the tricks and new things I learned that I had not seen previously. The nodeschool expressworks was difficult to understand without the video tutorials and I am not sure I leaned much from it.

**Comment by Obleo33** [comment]
[JS30](https://github.com/Obleo33/JavaScript30.git)

[WesBos Redux](https://github.com/Obleo33/Learn-Redux-Starter-Files.git)


![Master Express](http://imgur.com/6ENdsUQ.jpg)


![Scopes-Chains-Closures](http://imgur.com/qFyPbJd.jpg)

- Wes Bos is great however the Redux lesson was a bit too fast for me . I plan to work my way through the React lesson to firm up the basics.

-  JS 30 was great and I hope to work through the rest of the lessons as a warm up 

- Scopes-Chains-Closures was a good review.

- The Express tutorial wasn't much help. I felt lost the whole time and had to follow the videos.

**Comment by hmorri32** [comment]
[JS30 repo](https://github.com/hmorri32/JavaScript30)
[reduxtagram repo](https://github.com/hmorri32/Learn-Redux-Starter-Files)

<img width="625" alt="screen shot 2017-03-12 at 1 53 40 pm" src="https://cloud.githubusercontent.com/assets/20346065/23836275/5c1ae99c-073b-11e7-8370-5c00b257539b.png">

<img width="601" alt="screen shot 2017-03-12 at 2 12 00 pm" src="https://cloud.githubusercontent.com/assets/20346065/23836278/620c9530-073b-11e7-8479-4285e6e93a12.png">

Wes Bos is the man and his JS30 exercises were fantastic. Reduxtagram was a bit rushed although thorough and informative. I find nodeschool to be very hit or miss. The scopes and closures tutorial was a soft hit while the express tutorial was a nightmare.

**Comment by thatPamIAm** [comment]
[WesBos Repo](https://github.com/thatPamIAm/WesBos-Github-Repo)
[JS30 Repo](https://github.com/thatPamIAm/JavaScript30)

![Screenshot of NodeSchool](http://i.imgur.com/tr9m5sL.png)
![Screenshot of NodeSchool](http://i.imgur.com/02rK1uY.png)

I really enjoyed the tutorials from WesBos. He could be a bit fast at times (I found myself pausing and re-watching much of the material) but it was still very good information. The scopes and closures tutorial was pretty decent - but I felt completely lost during the JS Express tutorial.

**Comment by zkc** [comment]
[JS30](https://github.com/zkc/JavaScript30)
[Zucktagram](https://github.com/zkc/Learn-Redux-Starter-Files)


![scope](http://i.imgur.com/VAhMVs8.png)
![express](http://i.imgur.com/Q3ZIeqB.png)


Wes Bos's site gave me a bad first impression, to me it felt just like a "get rich quick" scam website. His video's were pretty solid, I liked the JS30 exercises the best. The redux was a great intro, I better understand high-level on how redux uses the store, actions, reducers etc. but I don't feel like I firmly grasp what each module is doing and couldn't fully piece them together yet without a reference like Mr. Bos. I liked both the nodeschool tutorials. I felt the Express tutorial assumed the participant has a stronger knowledge of how servers work than I currently do. The video explanations helped, but for many example I basically had to start with the answer and work backwards to figure it out.

**Comment by tbrandle** [comment]
[Reduxstagram](https://github.com/tbrandle/Reduxstagram)
[Javascript30](https://github.com/tbrandle/javascript30)
<img width="493" alt="screen shot 2017-03-12 at 10 03 02 pm" src="https://cloud.githubusercontent.com/assets/20690181/23841263/a48ccf66-0771-11e7-97d1-b36075e096ca.png">
<img width="484" alt="screen shot 2017-03-12 at 1 36 34 pm" src="https://cloud.githubusercontent.com/assets/20690181/23841270/a79a7488-0771-11e7-9eb9-132d72e2f709.png">


overall, I thought the prework was good.  I really like everything Wes Bo....wasn't a huge fan of the Express tutorial. It was pretty dry going through the videos compared to Wes Bo. I plan on working through the other Javascript30 tutorials as well. Very helpful.

**Comment by dunncl15** [comment]
<img width="438" alt="screen shot 2017-03-12 at 10 24 03 pm" src="https://cloud.githubusercontent.com/assets/17307269/23841422/c49ea79c-0772-11e7-9463-d3432d1827f0.png">

[JavaScript30](https://github.com/dunncl15/js30)

I thought the scope-chains-closures exercise was decent, but it could have been longer and progressed in difficulty. For a complicated topic, it kept things pretty entry level. The JS30 series was great. I really enjoyed creating some cool UI features with JS and CSS. The redux tutorial was good to watch to get an idea of what redux is, but not sure how useful it is as a code along. I decided it was more worthwhile to watch for a high-level understanding than to try to code along and regurgitate his code. If anything it made me want to take his react for beginners course. 

I was totally lost on the express exercise from the get go. There has to be better intro's to express out there than that.

**Comment by marissa27** [comment]
[Redux](https://github.com/marissa27/Wes-Bos-Redux-Tutorial)
[JS30](https://github.com/marissa27/JS30-repo)
<img width="488" alt="screen shot 2017-03-06 at 1 16 03 pm" src="https://cloud.githubusercontent.com/assets/20496360/23841836/bbffb196-0775-11e7-827d-fba8bf014807.png">
<img width="491" alt="screen shot 2017-03-12 at 3 24 15 pm" src="https://cloud.githubusercontent.com/assets/20496360/23841837/bc02061c-0775-11e7-8998-d48c3f5e552a.png">

The JS30 was awesome and something I definitely want to keep doing and maybe redo some. 
The redux was great, but went really fast so I think it would be helpful to still go over what we should have gotten out of it. 
The node scopes was a good refresher, but the express one totally went over my head. If not for the videos I don't think I would have gotten through it.
