### ISSUE TITLE
How I Start (optional)

### ISSUE THREAD

**Issue by EmilyMB** [turingschool/intermission-assignments#15]
Optional discussion here about [How I Start](https://howistart.org/posts/ruby/1) (Building a Ruby Gem) by Steve Klabnik.

**Comment by nathanows** [comment]
Good read, talks about a lot of just general good Ruby syntax which is good to read through every once and a while. Probably could have been helpful from a framework perspective when writing the Jetfuel wrapper gem.

Sidenote: This linked article was interesting on clarifying what Gemfile, Gemfile.lock and gemspec files do: http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/
