### ISSUE TITLE
Complete the Test-Driven JavaScript Assessment

### ISSUE THREAD

**Issue by stevekinney** [turingschool/intermission-assignments#18]

**Comment by jgujgu** [comment]
https://github.com/jgu2160/js-assessment

**Comment by DSynergy** [comment]
https://github.com/DSynergy/js-assessment

**Comment by kyrasteen** [comment]
https://github.com/kyrasteen/js-assessment

**Comment by paulgrever** [comment]
https://github.com/paulgrever/js-assessment

**Comment by indiesquidge** [comment]
https://github.com/indiesquidge/js-assessment

**Comment by neslom** [comment]
https://github.com/neslom/js-assessment

**Comment by kpearson** [comment]
https://github.com/kpearson/js-assessment

**Comment by mcshakes** [comment]
https://github.com/mcshakes/js-assessment

**Comment by rshea303** [comment]
https://github.com/rshea303/js-assessment

**Comment by treyx** [comment]
https://github.com/treyx/js-assessment

**Comment by mirjoy** [comment]
https://github.com/mirjoy/js-assessment

**Comment by AllPurposeName** [comment]
https://github.com/AllPurposeName/js-assessment

**Comment by gravitinos** [comment]
https://github.com/xvalentino/js-assessment
