### ISSUE TITLE
Complete the Test-Driven JavaScript Assessment

### ISSUE THREAD

**Issue by worace** [turingschool/intermission-assignments#20]
Please add the link to your repo in the comments

**Comment by loriculberson** [comment]
https://github.com/loriculberson/js-assessment

**Comment by kristinabrown** [comment]
https://github.com/kristinabrown/js-assessment

**Comment by Carmer** [comment]
https://github.com/carmer/js-assessment

**Comment by kylehenson** [comment]
https://github.com/kylehenson/js-assessment

**Comment by haveanicedavid** [comment]
https://github.com/davedan7/js-assessment

**Comment by tessgriffin** [comment]
https://github.com/tessgriffin/js-assessment

**Comment by tleskin** [comment]
https://github.com/tleskin/js-assessment

**Comment by mihir787** [comment]
https://github.com/mihir787/js-assessment.git

**Comment by michelleambrisco** [comment]
https://github.com/MichelleGolle/js-assessment

**Comment by tracycaruso** [comment]
https://github.com/tracycaruso/js-assessment
