### ISSUE TITLE
Sean Griffin's Using arel (optional)

### ISSUE THREAD

**Issue by worace** [turingschool/intermission-assignments#23]
Discuss Using Arel to Compose SQL Queries here.

**Comment by adamki** [comment]
Hmm, I had no clue that this was possible. If I understand correctly, Arel is a way to abstract SQL queries.

In some previous attempts, I had tried the AR method `.to_sql` and things blew up as I was instantly dealing with foreign objects(I think the were PSQL objects?). So, I do like the idea of using an `arel::table` class to handle complext queries. I did some additional reading and found that in many cases, AR can deliver the results for simple DB queries, but in cases where DB queries require more complex queries such as: 

*queries containing `OR` 
*queries with heavy string interpolation

It is best to use AREL.
