### ISSUE TITLE
Mary Rose Cook Live-Coding

### ISSUE THREAD

**Issue by worace** [turingschool/intermission-assignments#29]
Discuss [Mary Rose Cook's live coding](https://vimeo.com/105955605) here!

**Comment by kristinabrown** [comment]
I don't know what there is to discuss, I mean, it was pretty straight forward...

**Comment by michelleambrisco** [comment]
Not a lot to add to the discussion but I did enjoy watching this. It was cool to see the game being made from start to finish.

**Comment by tleskin** [comment]
Yeah. A little complicated, since I've never done anything like that in JS, but it seemed pretty simple and everything she did was straight forward.
