### ISSUE TITLE
Simplicity Matters by Rich Hickey (optional)

### ISSUE THREAD

**Issue by worace** [turingschool/intermission-assignments#31]
[Simplicity Matters by Rich Hickey](https://www.youtube.com/watch?v=rI8tNMsozo0) - As we move into working on larger and more sophisticated systems, some of the approaches that have worked on smaller projects may no longer be so effective. What does Rich Hickey say about the common pitfalls of Ruby and Rails applications?

**Comment by rasensio1** [comment]
Fully convinced to start learning clojure for real

**Comment by rasensio1** [comment]
Also, on the OO thing, where he talks about pointless wrapping methods in classes, that should just be functions. Relates to DHH talk on Ruby Rogues, where he talks about OO "rules" and why they aren't always the best choice.

**Comment by stevekinney** [comment]
@rasensio1 One of the cool things about JavaScript is that it's both object-oriented _and_ functional, which allows you to choose the best tool for the job. A few other languages share this train: Scala and Swift come to mind.
