### ISSUE TITLE
Real Software Engineering by Glenn Vanderburg (optional)

### ISSUE THREAD

**Issue by worace** [turingschool/intermission-assignments#33]
[Real Software Engineering by Glenn Vanderburg](https://www.youtube.com/watch?v=NP9AIUT9nos) - What does Glenn have to say about Software Engineering as a discipline? How does Software Engineering differ fundamentally from other Engineering disciplines? What can we as Software Engineers take away from other disciplines?

**Comment by George-Hudson** [comment]
"The cost of long feedback loops"
This is the 'technical debt' Jeff C. was talking about WAY back in module 1. It made sense then and makes more sense now.

**Comment by George-Hudson** [comment]
As we make testing cheaper and easier to use it reduces the need to create complex formal analysis beforehand.
