### ISSUE TITLE
jQuery fundamentals

### ISSUE THREAD

**Issue by worace** [turingschool/intermission-assignments#38]
Add any and all comments, questions, and other discussion for the jQuery Fundamentals course here.

**Comment by rasensio1** [comment]
What are we supposed to submit for this? Are there exercises?

**Comment by stevekinney** [comment]
Nah, but I would appreciate your thoughts, questions, and discussion points.

**Comment by 7hoenix** [comment]
$(...) is short for $( document ).ready(function {...});

Cool.

**Comment by stevekinney** [comment]
Yea. I dig it. You probably won't see me use it because I prefer the clarity when teaching. But, it's totally valid and cool. I am also old school and just do it the other way out of force of habit.

**Comment by selfup** [comment]
Is it cool to use the new ES6 syntax with jQuery? I kind of really like it

**Comment by stevekinney** [comment]
@selfup jQuery is just JavaScript. So, whatever the browser platform supports, you can use. Alternatively, you can use Babel and use all the latest and greatest ES6 and ES7 today and it will compile down to ES5.

**Comment by selfup** [comment]
Will look into Babel! Thanks
