### ISSUE TITLE
javascripting course

### ISSUE THREAD

**Issue by worace** [turingschool/intermission-assignments#39]
Submit the link to your Javascripting repo here.

**Comment by selfup** [comment]
I am leaving a comment:

https://github.com/selfup/javascripting

**Comment by 7hoenix** [comment]
https://github.com/jphoenix86/javascripting

**Comment by roseak** [comment]
https://github.com/roseak/javascripting

**Comment by jbrr** [comment]
https://github.com/jbrr/javascripting

**Comment by mbburch** [comment]
https://github.com/mbburch/javascripting

**Comment by MowAlon** [comment]
https://github.com/MowAlon/javascripting

**Comment by jxandery** [comment]
https://github.com/jxandery/javascripting

**Comment by plato721** [comment]
https://github.com/plato721/javascripting

**Comment by George-Hudson** [comment]
https://github.com/Egogre/javascripting
