### ISSUE TITLE
lololodash

### ISSUE THREAD

**Issue by worace** [turingschool/intermission-assignments#40]
Submit the link to your lololodash assignments here.

**Comment by rasensio1** [comment]
https://github.com/rasensio1/lololodash

**Comment by jbrr** [comment]
https://github.com/jbrr/lololodash (WIP)

**Comment by roseak** [comment]
https://github.com/roseak/lololodash (WIP)

**Comment by mbburch** [comment]
https://github.com/mbburch/lololodash

**Comment by plato721** [comment]
https://github.com/plato721/lololodash

**Comment by 7hoenix** [comment]
https://github.com/jphoenix86/lodash

**Comment by 7hoenix** [comment]
Questions:

What is a callback?

This expression from the lodash documentation feels super weird to me...
_.reduce(collection, [iteratee=_.identity], [accumulator], [thisArg])

Why are individual elements wrapped in [ ]'s (thisArg, accumulator, etc.)?
What is _.identity ? Assuming its just the yielded value from the collection... why is it prefaced with the same underscore like a typical lodash function?

**Comment by MowAlon** [comment]
https://github.com/MowAlon/lololodash

**Comment by George-Hudson** [comment]
https://github.com/Egogre/lololodash

**Comment by George-Hudson** [comment]
You probably figured this out by now.

"What is a callback?"

From my understanding, since functions can be traded around like objects, a callback is passing a function to another function and calling it from within that second function.

**Comment by selfup** [comment]
https://github.com/selfup/lololodash

Used new ES6 features, and tried out some npm styling conventions!

**Comment by stevekinney** [comment]
@Egogre That's probably one of the best explanations I've seen.
