### ISSUE TITLE
Exercisms 

### ISSUE THREAD

**Issue by biglovisa** [turingschool/intermission-assignments#49]
Submit a gist here comparing JavaScript exercism exercises you've completed with five other submissions. [Here](https://gist.github.com/tgraham777/9f284f096ba9da89a159) is an example of what we expect.

**Comment by amcrawford** [comment]
https://gist.github.com/amcrawford/e3e03be612fc27249d4a

**Comment by robbielane** [comment]
https://gist.github.com/robbielane/095ce464456789688959

**Comment by adamki** [comment]
https://gist.github.com/adamki/3f150f667f2e7808ee4c

**Comment by rossedfort** [comment]
https://gist.github.com/rossedfort/7614482867f8e8696665

**Comment by matt-stj** [comment]
https://gist.github.com/matt-stj/43b1ed13ec3836c3b557

**Comment by acareaga** [comment]
https://gist.github.com/acareaga/eb0023ad1680241845b1

**Comment by toriejw** [comment]
https://gist.github.com/toriejw/9dcce5f47710c23abc0c

**Comment by Kealii** [comment]
https://gist.github.com/Kealii/7ff52ba9199d44174516

**Comment by emilyfreeman** [comment]
https://gist.github.com/emilydowdle/c39b7642dda87ee7f4ca

**Comment by jillmd501** [comment]
https://gist.github.com/jillmd501/abc36d28d9e3392d4bd5

**Comment by patwey** [comment]
https://gist.github.com/patwey/db27840c0217aef5a8a5

**Comment by MattRooney** [comment]
https://gist.github.com/MattRooney/342e0843e1a5c869734c

**Comment by jasonpilz** [comment]
https://gist.github.com/jasonpilz/e9cd9321f3b5f3c9a549

**Comment by sekharp** [comment]
https://gist.github.com/sekharp/d6a4d5c86330fef3c2e3
