### ISSUE TITLE
Reading Option 1: JavaScript Allongé

### ISSUE THREAD

**Issue by stevekinney** [turingschool/intermission-assignments#5]
Read [JavaScript Allongé](https://leanpub.com/javascript-allonge/read) by Reginald Braithwaite

Discuss questions and thoughts here. Feel free to talk about the book as you're reading it. I'll also answer any questions you have.

Some things to think about:
- What new approaches to JavaScript did you pick up while reading this book?
- What concepts from the book might have an impact on the way you write Ruby?

**Comment by VikiAnn** [comment]
I'm really, really not good at reading tech books, apparently.

**Comment by VikiAnn** [comment]
Also, are the examples in this supposed to actually run on their own in Node? I tried typing one out and the console complained at me immediately about an unexpected token (

**Comment by stevekinney** [comment]
Code sample?

**Comment by VikiAnn** [comment]
function (d) {
  var calc = function (diameter) {
   var Pi = 3.14159265;

   return diameter \* Pi
 };

 return "The circumference is " + calc(d)
}

**Comment by VikiAnn** [comment]
Thing yelled at me before I could get past line 1 though...

**Comment by stevekinney** [comment]
Are you typing this in the REPL or running a file?

**Comment by VikiAnn** [comment]
I tried both.

**Comment by VikiAnn** [comment]
Also, ignore that that sample is from maaaaybe 25% through the book >_<

**Comment by stevekinney** [comment]
It looks like the issue is just that code is out of context of a runnable script. The JavaScript engine doesn't like that there is a lonely anonymous function just hanging out in the world. So, it sounds the alarms.

If you were to do something like this, it would work:

``` js
var calculateDiameter = function (d) {
  var calc = function (diameter) {
    var Pi = 3.14159265;

    return diameter * Pi
  };

  return "The circumference is " + calc(d)
}
```

The interpreter then sees you want to store it in a variable and is like—oh yea, totally legit.

Alternatively, you can use it as an [IIFE](http://benalman.com/news/2010/11/immediately-invoked-function-expression/):

``` js
(function (d) {
  var calc = function (diameter) {
    var Pi = 3.14159265;

    return diameter * Pi
  };

  return "The circumference is " + calc(d)
})(20)
```

**Comment by VikiAnn** [comment]
Huh. Weird. I guess that makes sense. I guess I was just figuring if it's in the book, it's runnable as-is.

Semi off-topic, how do you read a tech book? Do you try to just... read it? Or do you try typing out the examples even though the result's given in the book? Or something else? And does your strategy vary depending on whether it's a paper book or an e-book? I'm just finding it very difficult to stay focused on it.

**Comment by stevekinney** [comment]
I tend to—in my first pass—just read through the book and get a sense of the big picture. I liberally highlight and bookmark pages that I don't fully understand and return to them after I've gotten to the end of the book.
