### ISSUE TITLE
Reading Option 2: Speaking JavaScript

### ISSUE THREAD

**Issue by stevekinney** [turingschool/intermission-assignments#6]
Read [Speaking JavaScript](http://speakingjs.com/es5/) by Dr. Axel Rauschmayer.

Discuss the book, topics or concepts you found interesting here.

I'll also answer any questions you might have along the way.

**Comment by gregnar** [comment]
This is a good book about programming. His examples are useful; he follows an effective general-to-specific pattern for every topic, and his writing style is clear and deliberate without being dry. Nice book.
