### ISSUE TITLE
Uncaught ReferenceError: Invalid left-hand side in assignment

### ISSUE THREAD

**Issue by EndermanGalactic** [turingschool/intermission-assignments#60]
What am I doing wrong? :(  
 if(x_fridrihs<=99 && y_fridrihs<=420>280 || x_fridrihs<=599 && y_fridrihs<=770>630 || x_fridrihs=<749 && y_fridrihs<==570>430 || x_fridrihs<=799 && y_fridrihs<=420>280){
            Diena = Diena + 1;
            x_fridrihs = 450;
            y_fridrihs = 450;
            garums_veseliba = garums_veseliba + 4,1;
        }

**Comment by rrgayhart** [comment]
Can you let us know what this is in reference to? A particular lesson?
