### ISSUE TITLE
Build Jet Fuel

### ISSUE THREAD

**Issue by stevekinney** [turingschool/intermission-assignments#7]
You'll be building a modified version of [Jet Fuel](https://gist.github.com/stevekinney/cac8d9374e99a0d7d4b2).

Post a link to your repository here by Monday, 3/23.

The project itself is due Monday, 3/30.

**Comment by oorion** [comment]
Should we be using javascript to do anything other than filtering by search term?

**Comment by stevekinney** [comment]
It's up to you.

**Comment by AdamSmith910** [comment]
https://github.com/AdamSmith910/JetFuel

**Comment by EmilyMB** [comment]
https://github.com/EmilyMB/jet-fuel

**Comment by oorion** [comment]
https://github.com/oorion/jet_fuel

**Comment by laurawhalin** [comment]
https://github.com/laurawhalin/jet_fuel

**Comment by Lydias303** [comment]
https://github.com/Lydias303/url-strytta

**Comment by Jwan622** [comment]
https://github.com/Jwan622/jetfuel

**Comment by bryceholcomb** [comment]
https://github.com/bryceholcomb/jet_fuel

**Comment by nathanows** [comment]
Front-end
https://github.com/ndwhtlssthr/jetfuel-angular

API
https://github.com/ndwhtlssthr/jetfuel-rails

Wrapper Gem
https://github.com/ndwhtlssthr/jetfuel-gem

**Comment by bhargavisatpathy** [comment]
Web + API
https://github.com/bhargavisatpathy/jet_fuel

jetfuel Gem
https://github.com/bhargavisatpathy/jetfuel_gem

**Comment by mikedao** [comment]
https://github.com/mikedao/jetfuel

**Comment by KristaANelson** [comment]
https://github.com/KristaANelson/jet-fuel

**Comment by bmrsny** [comment]
https://github.com/bmrsny/jet_fuel

**Comment by Jwan622** [comment]
Groan....

**Comment by scottcrawford03** [comment]
https://github.com/scottcrawford03/jet_fuel

**Comment by cluhring** [comment]
https://github.com/cluhring/jet-fuel

**Comment by scottalexandra** [comment]
https://github.com/scottalexandra/jet-fuel
