### ISSUE TITLE
Shop Talk: Tom Dale (optional)

### ISSUE THREAD

**Issue by rrgayhart** [turingschool/intermission-assignments#72]
Optional discussion here about Shop Talk: Tom Dale (1.5 hours).

Do you agree with Tom? What parts of his argument are compelling? What parts do you disagree with?

**Comment by damwhit** [comment]
I really enjoyed listening to this podcast.  I can't say that I agree or disagree with Tom as I have never used a js framework.  I will say after listening that it does sound like it would be extremely helpful to use one and I do really love the idea of having a client side js app simply speaking to another server side app that serves up an api.  I can't wait to try some frameworks out!  I also thought it was interesting that he mentioned react and native a few times without bashing them, however he did not seem to be a fan of angular.  I've been most interested in trying react/native, but this did peak my interest in ember.  What frameworks do you like most and why?
