### ISSUE TITLE
Mary Rose Cook

### ISSUE THREAD

**Issue by EmilyMB** [turingschool/intermission-assignments#8]
Discuss [Mary Rose Cook's live coding](https://vimeo.com/105955605) here!

**Comment by EmilyMB** [comment]
I thought this was kind of cute, but I kept thinking, "Where are the tests????".  But, good job for her to be brave enough to live code a game in front of a roomful of people.

**Comment by KristaANelson** [comment]
My biggest pet peeve about live coding is there is never any tests!! The process flow for me is so important and i would rather see less with tests or sit through a longer talk.

**Comment by bmrsny** [comment]
I felt pretty lost. I think I get the overall picture, but she codes pretty quick. May need to take a second look at this after practicing more JavaScript. I also would have liked to see tests, may have helped me see the architecture of the program.

**Comment by DSynergy** [comment]
woah

I understood the basic concepts as she talked through them, but all the moving pieces and math were a bit much

Cool to see it can be done though
