### ISSUE TITLE
JavaScripting

### ISSUE THREAD

**Issue by rrgayhart** [turingschool/intermission-assignments#80]
Submit the link to your javascripting exercise here.

**Comment by notmarkmiranda** [comment]
https://github.com/notmarkmiranda/javascripting

**Comment by s-espinosa** [comment]
https://github.com/s-espinosa/javascripting

**Comment by thomschlereth** [comment]
https://github.com/thompickett/javascripting

**Comment by ghost** [comment]
https://github.com/Salvi6God/javascripting

**Comment by pindell-matt** [comment]
https://github.com/pindell-matt/javascripting

**Comment by theonlyrao** [comment]
https://github.com/theonlyrao/javascripting

**Comment by chadellison** [comment]
https://github.com/chadellison/javascripting

**Comment by Claudia108** [comment]
https://github.com/Claudia108/javascripting

**Comment by jdliss** [comment]
https://github.com/jdliss/javascripting

**Comment by lingtran** [comment]
https://github.com/lingtran/javascripting.git

**Comment by kristindiannefoss** [comment]
https://github.com/kristindiannefoss/javascripting

**Comment by alirezaandersen** [comment]
https://github.com/alirezaandersen/javascripting-.git

**Comment by jeneve** [comment]
https://github.com/jeneve/javascripting

**Comment by marinacor1** [comment]
https://github.com/marinacor1/javascripting

**Comment by patrickwhardy** [comment]
https://github.com/patrickwhardy/javascripting

**Comment by jwashke** [comment]
https://github.com/jwashke/javascripting

**Comment by kamiboers** [comment]
https://github.com/kamiboers/javascripting

**Comment by drew-t** [comment]
https://github.com/drew-t/javascripting

**Comment by GKhalsa** [comment]
https://github.com/GKhalsa/javascripting

**Comment by JaredRoth** [comment]
https://github.com/JaredRoth/javascripting
