### ISSUE TITLE
NodeSchool for 1606-F

### ISSUE THREAD

**Issue by stevekinney** [turingschool/intermission-assignments#85]
Submit the link to your exercises here.

Please work through _all four_ of the following courses:
- [Promise It Won't Hurt](https://github.com/stevekane/promise-it-wont-hurt)
- [Lololodash](https://github.com/mdunisch/lololodash)
- [Scope Chains and Closures](https://github.com/jesstelford/scope-chains-closures)
- [ExpressWorks](https://github.com/azat-co/expressworks)

**Comment by Jeff-Duke** [comment]
https://github.com/Jeff-Duke/mod-3-prework

**Comment by kylem038** [comment]
https://github.com/kylem038/mod-3-prework

**Comment by swanie21** [comment]
https://github.com/swanie21/module-3-prework

**Comment by mjvalade** [comment]
https://github.com/mjvalade/pre-work-mod3

**Comment by Peter-Springer** [comment]
https://github.com/Peter-Springer/mod3-prework

**Comment by bretthev** [comment]
https://github.com/bretthev/mod3-prework

**Comment by kccrs** [comment]
https://github.com/kccrs/lololodash
https://github.com/kccrs/scope-chains-closures
https://github.com/kccrs/promise-shop
https://github.com/kccrs/expressworks

**Comment by 07nguyenpaul** [comment]
https://github.com/07nguyenpaul/prework-module-3

**Comment by madison-codes** [comment]
https://github.com/madison-kerndt/mod-3-preWork

**Comment by ab255** [comment]
https://github.com/ab255/mod-3-prework

**Comment by bgdfry** [comment]
https://github.com/bcgodfrey91/mod-three-prework/

**Comment by blakeworsley** [comment]
https://github.com/blakeworsley/mod-3-prework

**Comment by kerrd89** [comment]
https://github.com/kerrd89/module-3-prework

**Comment by sikemausa** [comment]
https://github.com/sikemausa/intermission
