### ISSUE TITLE
Nodeschool.io

### ISSUE THREAD

**Issue by neight-allen** [turingschool/intermission-assignments#88]
Submit the link to your exercises here.

Please work through _at least two_ of the following courses:
- [javascripting](https://github.com/sethvincent/javascripting)
- [lololodash](https://github.com/mdunisch/lololodash)
- [ExpressWorks](https://github.com/azat-co/expressworks)

**Comment by kjs222** [comment]
Lololodash: https://github.com/kjs222/lololodash
ExpressWorks: https://github.com/kjs222/expressworks
Javascripting: https://github.com/kjs222/javascripting

**Comment by ryanflach** [comment]
JavaScripting: https://github.com/ryanflach/javascripting
Lololodash: https://github.com/ryanflach/lololodash
ExpressWorks: https://github.com/ryanflach/expressworks

**Comment by dtinianow** [comment]
https://github.com/dtinianow/javascripting
https://github.com/dtinianow/lololodash
https://github.com/dtinianow/expressworks

**Comment by pwentz** [comment]
Javascripting: https://github.com/pwentz/javascripting
Lololodash: https://github.com/pwentz/lololodash

**Comment by Automatic365** [comment]
Javascripting: https://github.com/Automatic365/javascripting
Expressworks: https://github.com/Automatic365/expressworks

**Comment by cconcannon** [comment]
javascripting: https://github.com/concach/javascripting
expressworks: https://github.com/concach/expressworks

**Comment by allindow** [comment]
javascripting: https://github.com/allindow/javascripting
lololodash: https://github.com/allindow/lololodash

**Comment by kbs5280** [comment]
javascripting: https://github.com/kbs5280/javascripting
expressworks: https://github.com/kbs5280/expressworks-solutions

**Comment by matthewrpacker** [comment]
javascripting: https://github.com/matthewrpacker/javascripting
lololodash: https://github.com/matthewrpacker/lololodash

**Comment by zackforbing** [comment]
javascripting: https://github.com/zackforbing/javascripting
expressworks: https://github.com/zackforbing/expressworks

**Comment by MsJennyGiraffe** [comment]
javascripting: https://github.com/MsJennyGiraffe/javascripting
expressworks: https://github.com/MsJennyGiraffe/expressworks

**Comment by livecodelife** [comment]
javascripting: https://github.com/Caleb9193/javascripting
lololodash: https://github.com/Caleb9193/lololodash

**Comment by chompasina** [comment]
Javascripting: https://github.com/chompasina/javascripting
Lololodash: https://github.com/chompasina/javascripting

**Comment by deborahleehamel** [comment]
javascripting: https://github.com/deborahleehamel/javascripting
lololodash: https://github.com/deborahleehamel/lololodash

**Comment by roscalabrin** [comment]
javascripting: https://github.com/roscalabrin//javascripting
lololodash: https://github.com/roscalabrin/lololodash

**Comment by karinamzalez** [comment]
javascripting: https://github.com/karinamzalez/javascripting
lololodash: https://github.com/karinamzalez/lololodash

**Comment by Laner12** [comment]
JavaScripting: https://github.com/Laner12/javascripting
lololodash: https://github.com/Laner12/lololodash
expressworks: coming soon

**Comment by twhitinger** [comment]
JavaScripting: https://github.com/twhitinger/javascripting
lololodash: https://github.com/twhitinger/lololodash

**Comment by 5Notes** [comment]
Javascripting: https://github.com/Yoyo2Code/javascripting
lololodash: https://github.com/Yoyo2Code/lololodash
