### ISSUE TITLE
Intermission Assignments for 1608-F

### ISSUE THREAD

**Issue by martensonbj** [turingschool/intermission-assignments#97]
Submit your work from intermission assignments in a comment below.

**Comment by kswhyte** [comment]
<img width="491" alt="screen shot 2016-11-25 at 12 20 04 pm" src="https://cloud.githubusercontent.com/assets/13802107/20634029/b9cb3e60-b309-11e6-9744-235e9dc9bf00.png">

<img width="556" alt="promise-it-wont-hurt-kwhyte" src="https://cloud.githubusercontent.com/assets/13802107/20634035/bdc0e6be-b309-11e6-91fb-3cca2b5ed536.png">

**Comment by kswhyte** [comment]
There were some issues with 'Throw an error' and 'An important rule' which could not be resolved for some reason, even with said solutions and other resources that were consulted.

**Comment by rcwestlake** [comment]
https://github.com/rcwestlake/mod-3-prework

Same note as Kinan, two of the Promise lessons could not be resolved.

**Comment by gness1804** [comment]
https://github.com/gness1804/mod-3-prework

Two broken promises like the others...seems to be a bug with their program. The Scopes and Closures course was really good, though!

**Comment by ianlancaster** [comment]
![screen shot 2016-11-26 at 5 30 11 pm](https://cloud.githubusercontent.com/assets/5510256/20644780/d4759be2-b3ff-11e6-8138-139dd72a4c83.png)
![screen shot 2016-11-26 at 5 42 38 pm](https://cloud.githubusercontent.com/assets/5510256/20644781/d482f80a-b3ff-11e6-9896-10058a1304de.png)

**Comment by ChelseaSkovgaard** [comment]
<img width="530" alt="screen shot 2016-11-27 at 8 27 37 am" src="https://cloud.githubusercontent.com/assets/18074889/20649361/81dbabc0-b47b-11e6-8081-772b955b68c3.png">
<img width="518" alt="screen shot 2016-11-27 at 8 30 10 am" src="https://cloud.githubusercontent.com/assets/18074889/20649370/c6e343d6-b47b-11e6-9ef0-98da59221212.png">
<img width="521" alt="screen shot 2016-11-27 at 8 29 40 am" src="https://cloud.githubusercontent.com/assets/18074889/20649371/cc9db45a-b47b-11e6-9c9d-2c8cb6a5425e.png">

**Comment by maiastone** [comment]
https://github.com/maiastone/mod-3-prework

**Comment by kswhyte** [comment]
<img width="485" alt="lololodash tutorial-kw" src="https://cloud.githubusercontent.com/assets/13802107/20651874/069600f2-b4ab-11e6-8225-9f4764ddedc7.png">

**Comment by hilarylewis92** [comment]
https://github.com/hilarylewis92/mod-3-prework

**Comment by lrknaff** [comment]
https://github.com/lrknaff/intermission-m3

**Comment by gprocell927** [comment]
[Gabi's sad attempts at prework](https://github.com/gprocell927/mod-3-prework)

**Comment by kristenburgess25** [comment]
![preworkproof](https://cloud.githubusercontent.com/assets/16327667/20653491/6dc15004-b4cb-11e6-8037-ae12370084cc.jpg)

**Comment by kswhyte** [comment]
<img width="485" alt="expressj-kw" src="https://cloud.githubusercontent.com/assets/13802107/20653505/86a5ab9c-b4cb-11e6-89af-9a3f6da9bf12.png">

**Comment by nnchambs** [comment]
<img width="485" alt="screen shot 2016-11-27 at 9 24 32 pm" src="https://cloud.githubusercontent.com/assets/17344915/20656570/921c48e4-b4eb-11e6-9194-12a964b92c96.png">
<img width="485" alt="screen shot 2016-11-27 at 9 49 58 pm" src="https://cloud.githubusercontent.com/assets/17344915/20656571/95e35daa-b4eb-11e6-9729-cb40fea18efd.png">
<img width="479" alt="screen shot 2016-11-27 at 9 40 57 pm" src="https://cloud.githubusercontent.com/assets/17344915/20656573/97a5a724-b4eb-11e6-8524-375e65d99ee9.png">
