### ISSUE TITLE
Intermission Assignments 1610-FE

### ISSUE THREAD

**Issue by martensonbj** [turingschool/intermission-assignments#98]
Module 3 Front End Prework:   

Leave links to github repos, gists, or screenshots in the comments below. Good resources for screenshots are [recordit](http://recordit.co/) or [imgur](http://imgur.com/).   

**Required Assignments**: 
1. Wes Bos Redux Tutorial  
2. NodeSchool Tutorials  
3. JavaScript 30 Exercises  

Please note any additional or optional work completed - feel free to add feedback on any exercises that went well/didn't go well here also.

**Comment by sljohnson32** [comment]
**Wes Bos Redux Tutorial**
Here is a quick recordit of the final site I built and a quick rundown of all the completed videos.  Let me know if this is not what you're looking for! http://recordit.co/nohNKBC3WA
REPO:  https://github.com/sljohnson32/Learn-Redux-Starter-Files

**JS30**
REPO: https://github.com/sljohnson32/JavaScript30

**NodeSchool.io**
Coming soon...

**Comment by apsitos** [comment]
Hi Brenna, I've finished the Wes Bos tutorial. My repo is [here](https://github.com/apsitos/LearnRedux). Please let me know if you'd like me to do a recordit of the final site!
NodeSchool lessons [here](https://gist.github.com/apsitos/f3a3978a614433dbf8aa58321850cb49)
JavaScript 30 repo [here](https://github.com/apsitos/JS30)
- I did 1, 4, 5, 6, 7, 9, 14, 17, 24, 25

**Comment by chelletuerk** [comment]
To: Brenna
https://github.com/chelletuerk/redux_tutorial
Love: chelle

**Comment by adam-rice** [comment]
@martensonbj 🔥  🚒  :woman_firefighter: 🔥 
https://github.com/adam-rice/redux-introduction-reduxstagram
https://github.com/adam-rice/JavaScript_challenges

**Comment by devinmarieb** [comment]
Pre-Work (I still have five more of the JS30 problems to do)
https://github.com/devinmarieb/mod3-prework

I also re did my personal site in React! 
https://devinmarieb.github.io/personal-portfolio/

**Comment by mlimberg** [comment]
JS-30: https://github.com/mlimberg/WesBos30JSChallenges
Redux Tutorial: https://github.com/mlimberg/WesBos-LearnRedux
Scopes-Chains-Etc: https://github.com/mlimberg/scope-chains-closures
ExpressJS: https://github.com/mlimberg/expressJS

**Comment by chelletuerk** [comment]
Javascript 30--I completed the following exercises: 4, 6, 7, 9, 14, 15, 18, 21, 24, 25

https://github.com/chelletuerk/javascript30

**Comment by jksmall0631** [comment]
[JS-30](https://github.com/jksmall0631/JS30)
[Redux](https://github.com/jksmall0631/redux-tutorial)
[SCCJS/Express](http://imgur.com/a/NUJGq)

**Comment by DanGrund** [comment]
Redux - [Redux Repo](https://github.com/DanGrund/WesBosRedux)
JS30 - [JS30 Repo](https://github.com/DanGrund/WesBosJavaScript)
SCC - [Scope Chains Repo](https://github.com/DanGrund/ScopeChains-Tut)
Express - started, but honestly just kinda confused on what express even is..

**Comment by stephanieea** [comment]
**Node JS**: https://github.com/StephanieEA/NodeJS-Exercises

  - I think more info about garbage collection would be helpful.

**JavaScript30**: https://github.com/StephanieEA/JavaScript30
  - I completed #2-7, 13, 14, 24, 25

**Learn Redux**: https://github.com/StephanieEA/Learn-Redux-Starter-Files/tree/completed

**Comment by chelletuerk** [comment]
Scope Chains Gist

https://gist.github.com/chelletuerk/f21c44eb5f5bdace0c5ef9bb6bb7c9b5#file-screen-shot-2017-01-22-at-12-25-34-pm

**Comment by pescel** [comment]
[JavaScript30](https://github.com/pescel/JavaScript30)
My extra 5 were 02, 05, 09, 12, & 27

[Redux](https://github.com/pescel/Learn-Redux-Starter-Files) 

[expressworks](https://github.com/pescel/expressworks)

[scopes-chains-closures](https://github.com/pescel/scope-chains-closures)

**Comment by noahpeden** [comment]
Redux: https://github.com/noahpeden/Learn-Redux-Starter-Files
JS 30: https://github.com/noahpeden/JavaScript30 : 1, 2, 3, 8, 20 were my extras
Expressworks: https://github.com/noahpeden/expressworks
SSC: https://github.com/noahpeden/scope-chains-closures

**Comment by chelletuerk** [comment]
Expressworks challenges gist

https://gist.github.com/chelletuerk/62e545f84f298513a120caa8dbc9868e

**Comment by JeffBuss** [comment]
### Mod 3 Prework
#### [Reduxstagram](https://github.com/JeffBuss/reduxstagram)

Fun, useful project. It's great to find yourself taking notes on sections you know you'll end up using in future projects. This will definitely be a great resource.

#### [Javascript30](https://github.com/JeffBuss/javascript30) 

Completed 3, 5, 9, 14, and 17 for my choose your own adventure mode. Really love how Wes presents these tutorials in easily-digestible, entertaining pieces. Lots of relevant exercises here, and I will definitely be completing more of these. Would recommend this to be presented even earlier on in the program, especially the exercises regarding handling arrays.

#### [Scope, Chains, and Closures](https://github.com/JeffBuss/scope-chains-closures)

I'm an idiot a lot of the time, and this seemed way too simplistic. I easily spent 5x more time wrestling w/ the terminal setup and figuring out how they wanted me to format everything than actually writing code. Garbage collection seemed useful, but I'll be looking for another source for info on this.

#### [ExpressJS](https://github.com/JeffBuss/expressjs)

Wut? I can assure you I didn't just rewrite the solution file in ES6 w/ semi-colons...

**Comment by dylanavery720** [comment]
[JavaScript30 (#1, #2, #9, Voiceanator, Whack-A-Mole)](https://github.com/dylanavery720/JavaScript30/tree/dylanavery)

[Learn Redux](https://github.com/dylanavery720/Learn-Redux-Starter-Files/tree/dylanavery)

[Scopes, Chains, Closures](http://imgur.com/a/4GBv6)

[ExpressJS](http://imgur.com/a/SLak0)

**Comment by ejwill04** [comment]
[Reduxstagram](https://github.com/ejwill04/Reduxstagram)

[JavaScript30](https://github.com/ejwill04/JS30)
I completed 2, 12, 17, 21, and 22 for my extras. 

[Scope-Chains-Closures](http://recordit.co/4voqCVQG9K)

[Expressworks](http://recordit.co/UsvwtrfTLu)

**Comment by bekahlundy** [comment]
Redux Tutorial: https://github.com/bekahlundy/learning-redux
JS30: https://github.com/bekahlundy/JavaScript-30
Scope, Chains, Closures: https://github.com/bekahlundy/scope-chain-closure-prework/tree/master/answers
Express: https://github.com/bekahlundy/expressworks-practice

**Comment by jwood11atx** [comment]
redux toot - https://github.com/jwood11atx/reduxstagram
js30 - https://github.com/jwood11atx/js30
scc - https://github.com/jwood11atx/Scope-Chains-Closures
express - didn't get far. honestly not really learning what's going on. found myself mindlessly typing.

**Comment by mziccardi** [comment]
Redux- https://github.com/mziccardi/reduxprework
